### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Zayelion** [bunsenbrowser/cordova-node-plugin#3]
Could we get a short explanation of how to use this to setup an express server in regular JavaScript?

**Comment by chrisekelley** [comment]
Check out Bunsen Browser - I have an express server here: https://github.com/bunsenbrowser/bunsen/tree/master/bunsen-ang/src/assets

**Comment by chrisekelley** [comment]
I just added a link to Bunsen and the node server example to the Readme.
